export let ActionTypes = {
	GET_WP_VARS: 'GET_WP_VARS',
	SET_CURRENT_PAGE_ID: 'SET_CURRENT_PAGE_ID',
	SET_MENU_TREE: 'SET_MENU_TREE',
	GET_PAGE_FROM_CACHE: 'GET_PAGE_FROM_CACHE',
	SET_PAGE_IN_CACHE: 'SET_PAGE_IN_CACHE',
	CACHE_UPDATED: 'CACHE_UPDATED'
};
